### ISSUE TITLE
[New game]: Surviving elements

### ISSUE THREAD

**Issue by S-ishita** [kunjgit/GameZone#1446]
### 🎮 Game Request

CONTROLS 

Arrows for move

Mouse to aim the target

Click left to shot with selected element

Click rigth to change element selected

The world was destroyed by the natural elements and you are the unique survivor.

Try to survive to the attack of the elements, using them!!!

You can change your weapon ( Water , Fire , Earth and Wind) using right click.

### Point down the features

Kill all element as you can and Survive!!!

But be careful if you make a mistake and attack a element with the same element, this will be stronger and faster, if two enemy elements collide between they these will have more power too.

Water kills fire
Fire kills earth
Earth kills wind
Wind kills water

Enjoy it!!!

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment]
Hey @S-ishita ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by 0xabdulkhalid** [comment]
Hello Sister 👋🏻 

- Hope you're doing well, Yesterday we both just spammed this whole repository by adding multiple issues and PR's
- So i have received warning from respected PA and Moderator also, and they told me to close all issues are pr's
- If we don't clear the spam we done then we will be blacklisted on the GSSOC's Contributors list
- Then our hardwork will be wasted in adding these games to this repository, I can understand we both invested so much of time to contribute here
- But this is an Do or Die situation, I hope you can understand
- I'm writing this here because there's no platform we can connect privately to send this text to you
- And I'm already closing the Issues and PR's so that i can't be blacklisted and banned, I thought to tell this to you because we both are spammed this repository.
- I would like both of us in GSSOC's Leaderboard, i don't want authorities to blacklist us.

Thank You!
